FROM node:18-alpine as builder

WORKDIR /home/app 
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


FROM node:18-alpine

WORKDIR /home/app
COPY package*.json ./
RUN npm install
COPY --from=builder /home/app/dist ./dist
COPY --from=builder /home/app/config ./config

EXPOSE 3000
CMD ["node", "dist/app.js"]
